/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 19 20:38:00 GMT 2026
 */

package calculadora;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import calculadora.Calculadora;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calculadora_ESTest extends Calculadora_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      calculadora0.dividir(1685, 1685);
      calculadora0.fatorial(1);
      calculadora0.dividir(2, (-1276));
      calculadora0.fatorial(0);
      calculadora0.subtrair(459, 459);
      int int0 = (-2627);
      calculadora0.dividir(0, 1);
      calculadora0.fatorial(0);
      calculadora0.fatorial(1);
      // Undeclared exception!
      try { 
        calculadora0.fatorial((-2016));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00FAmero negativo n\u00E3o permitido
         //
         verifyException("calculadora.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = calculadora0.subtrair(1923, 1923);
      calculadora0.dividir(0, 1923);
      calculadora0.fatorial(0);
      int int1 = calculadora0.dividir((-2180), (-964));
      assertEquals(2, int1);
      
      int int2 = calculadora0.dividir(580, 1923);
      assertTrue(int2 == int0);
      
      int int3 = calculadora0.fatorial(0);
      assertEquals(1, int3);
      
      int int4 = calculadora0.subtrair(1923, (-3252));
      assertEquals(5175, int4);
      
      calculadora0.dividir(0, (-3252));
      boolean boolean0 = calculadora0.isPar((-435));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = (-1);
      // Undeclared exception!
      try { 
        calculadora0.fatorial((-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00FAmero negativo n\u00E3o permitido
         //
         verifyException("calculadora.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = (-2790);
      calculadora0.dividir(1, 2);
      calculadora0.fatorial(602);
      calculadora0.subtrair((-2790), 1419);
      calculadora0.somar(1419, (-4209));
      // Undeclared exception!
      try { 
        calculadora0.fatorial((-2790));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00FAmero negativo n\u00E3o permitido
         //
         verifyException("calculadora.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      // Undeclared exception!
      try { 
        calculadora0.fatorial((-186));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00FAmero negativo n\u00E3o permitido
         //
         verifyException("calculadora.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      calculadora0.fatorial(0);
      int int0 = 0;
      // Undeclared exception!
      try { 
        calculadora0.dividir(0, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Divis\u00E3o por zero n\u00E3o permitida
         //
         verifyException("calculadora.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = 0;
      // Undeclared exception!
      try { 
        calculadora0.dividir(0, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Divis\u00E3o por zero n\u00E3o permitida
         //
         verifyException("calculadora.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      // Undeclared exception!
      try { 
        calculadora0.fatorial((-394));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00FAmero negativo n\u00E3o permitido
         //
         verifyException("calculadora.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = 0;
      // Undeclared exception!
      try { 
        calculadora0.dividir(0, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Divis\u00E3o por zero n\u00E3o permitida
         //
         verifyException("calculadora.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = 2018;
      calculadora0.dividir(2018, 2018);
      calculadora0.dividir(1, 1);
      int int1 = calculadora0.subtrair(567, 567);
      calculadora0.somar(1, 0);
      calculadora0.fatorial(int0);
      int int2 = 276;
      calculadora0.somar(int2, int1);
      int int3 = 0;
      calculadora0.fatorial(int3);
      int int4 = 0;
      calculadora0.fatorial(int4);
      int int5 = calculadora0.fatorial(int1);
      int int6 = (-1168);
      int int7 = 0;
      try {
          int7 = calculadora0.fatorial(int6);
          fail("Esperava uma IllegalArgumentException");
      } catch (IllegalArgumentException e) {
          // Teste passa - exceção esperada foi lançada
          assertEquals("Número negativo não permitido", e.getMessage());
      }
      calculadora0.somar(int5, int6);
      int int8 = (-103);
      int int9 = (-2461);
      calculadora0.subtrair(int8, int9);
      int int10 = 1268;

      try {
          calculadora0.dividir(int10, int4);
          fail("Esperava uma IllegalArgumentException");
      } catch (IllegalArgumentException e) {
          // Teste passa - exceção esperada foi lançada
          assertEquals("Divisão por zero não permitida", e.getMessage());
      }
      int int11 = 610;
      calculadora0.somar(int11, int7);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      calculadora0.isPar(2307);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      calculadora0.dividir(1, (-1));
      int int0 = (-1);
      // Undeclared exception!
      try { 
        calculadora0.fatorial((-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00FAmero negativo n\u00E3o permitido
         //
         verifyException("calculadora.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      calculadora0.dividir((-3658), (-3658));
      calculadora0.isPar(1756);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      calculadora0.fatorial(2);
      calculadora0.subtrair((-504), (-504));
      calculadora0.subtrair(0, 0);
      // Undeclared exception!
      try { 
        calculadora0.fatorial((-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00FAmero negativo n\u00E3o permitido
         //
         verifyException("calculadora.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      calculadora0.multiplicar(1, (-1821));
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      calculadora0.dividir((-1244), (-1456));
      calculadora0.dividir(0, (-1244));
      calculadora0.multiplicar(1487, 0);
      calculadora0.dividir(5070, 1487);
      calculadora0.dividir((-1356), 15);
      calculadora0.somar(2175, 0);
      calculadora0.isPar(2175);
      calculadora0.somar(0, 0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      calculadora0.fatorial(0);
      calculadora0.multiplicar(1050, 1050);
      calculadora0.isPar(0);
      calculadora0.subtrair(1, 1023);
      int int0 = 0;
      calculadora0.dividir(1023, 1050);
      calculadora0.isPar(0);
      int int1 = (-1480);
      calculadora0.multiplicar(1, (-1480));
      // Undeclared exception!
      try { 
        calculadora0.fatorial((-3364));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00FAmero negativo n\u00E3o permitido
         //
         verifyException("calculadora.Calculadora", e);
      }
  }
}
